  name: Go Test
  on: [push]
  jobs:
    build:
      name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          go_version: [1.23]
          os: [ubuntu-latest]

      steps:
        - name: Setup Go ${{ matrix.go_version }}
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go_version }}
          id: go

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Tidy the Go module
          run: |
            go mod tidy